nst_team_mapping = {
    "Minnesota Wild": "MIN",
    "Vegas Golden Knights": "VGK",
    "Ottawa Senators": "OTT",
    "Carolina Hurricanes": "CAR",
    "Columbus Blue Jackets": "CBJ",
    "Florida Panthers": "FLA",
    "Los Angeles Kings": "LA",
    "New Jersey Devils": "NJ",
    "Montreal Canadiens": "MTL",
    "Colorado Avalanche": "COL",
    "Washington Capitals": "WSH",
    "Detroit Red Wings": "DET",
    "Tampa Bay Lightning": "TB",
    "Vancouver Canucks": "VAN",
    "Dallas Stars": "DAL",
    "New York Rangers": "NYR",
    "Buffalo Sabres": "BUF",
    "Philadelphia Flyers": "PHI",
    "Edmonton Oilers": "EDM",
    "St Louis Blues": "STL",
    "Seattle Kraken": "SEA",
    "Toronto Maple Leafs": "TOR",
    "San Jose Sharks": "SJ",
    "Pittsburgh Penguins": "PIT",
    "Winnipeg Jets": "WPG",
    "Calgary Flames": "CGY",
    "Boston Bruins": "BOS",
    "Nashville Predators": "NSH",
    "Anaheim Ducks": "ANA",
    "Chicago Blackhawks": "CHI",
    "Arizona Coyotes": "ARI",
    "Utah Mammoth": "UTA",
    "Utah Hockey Club": "UTA",
    "New York Islanders": "NYI"
}