name: Build and Push Scraper Docker Image
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: false
        default: 1.0.0

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    ###
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      #
      - name: Setup Buildx for Docker
        uses: docker/setup-buildx-action@v3
      #
      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: sohraub/hockey-stats-web-scraper:${{ inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
    ###
