name: Test pybaseball in docker
on:
  push:
  workflow_dispatch:

jobs:
  rest:
    runs-on: ubuntu-latest
    container:
      image: sohraub/hockey-stats-web-scraper:main

    steps:
      - uses: actions/checkout@v4

      - name: Test library
        run: python3 test.py

