name: Test pybaseball in docker
on:
  push:
  workflow_dispatch:

jobs:
  rest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: ahhh
        run: ls -lrt

      - name: Test library
        run: python3 test.py

