name: Test pybaseball in docker
on:
  push:
  workflow_dispatch:

jobs:
  rest:
    runs-on: ubuntu-latest
    container:
      image: sohraub/hockey-stats-web-scraper:main

    steps:
      - name: Test library
        shell: python
        run: |
          import pybaseball as pyb
          df = pyb.schedule_and_record(2025, "TOR")
          print(df)

